version: '3'

services:
  nginx:
    image: nginx
    container_name: $APP_NAME-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mongo
    container_name: $APP_NAME-db
    restart: always
    # volumes:
    #   - ./configdb:/data/configdb
    #   - ./db:/data/db
    ports:
      - $DB_PORT:27017
    environment:
      MONGO_INITDB_DATABASE: $DB_NAME
    networks:
      - app_network

  app:
    build: ./app
    container_name: $APP_NAME-app
    restart: always
    depends_on:
      - db
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    environment:
      - APP_NAME=$APP_NAME
      - APP_PORT=$APP_PORT
      - APP_SECRET=$APP_SECRET
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
